import type { Account, Medicine } from "../types";

export const SEED_MEDICINES: Medicine[] = [
  {
    id: "med-001",
    name: "Paracetamol 500mg",
    category: "Analgesic",
    price: 5,
    quantity: 150,
    expiryDate: "2027-06-30",
    manufacturer: "GSK",
    lowStockThreshold: 10,
  },
  {
    id: "med-002",
    name: "Amoxicillin 250mg",
    category: "Antibiotic",
    price: 12,
    quantity: 80,
    expiryDate: "2026-12-31",
    manufacturer: "Pfizer",
    lowStockThreshold: 10,
  },
  {
    id: "med-003",
    name: "Ibuprofen 400mg",
    category: "Anti-inflammatory",
    price: 8,
    quantity: 7,
    expiryDate: "2027-03-15",
    manufacturer: "Reckitt",
    lowStockThreshold: 10,
  },
  {
    id: "med-004",
    name: "Omeprazole 20mg",
    category: "Antacid",
    price: 15,
    quantity: 60,
    expiryDate: "2027-01-20",
    manufacturer: "AstraZeneca",
    lowStockThreshold: 10,
  },
  {
    id: "med-005",
    name: "Cetirizine 10mg",
    category: "Antihistamine",
    price: 6,
    quantity: 5,
    expiryDate: "2026-09-30",
    manufacturer: "UCB",
    lowStockThreshold: 10,
  },
  {
    id: "med-006",
    name: "Metformin 500mg",
    category: "Antidiabetic",
    price: 10,
    quantity: 100,
    expiryDate: "2027-08-15",
    manufacturer: "Merck",
    lowStockThreshold: 10,
  },
  {
    id: "med-007",
    name: "Atorvastatin 20mg",
    category: "Cholesterol",
    price: 25,
    quantity: 45,
    expiryDate: "2027-05-10",
    manufacturer: "Pfizer",
    lowStockThreshold: 10,
  },
  {
    id: "med-008",
    name: "Amlodipine 5mg",
    category: "Antihypertensive",
    price: 18,
    quantity: 8,
    expiryDate: "2026-11-30",
    manufacturer: "Norvasc",
    lowStockThreshold: 10,
  },
  {
    id: "med-009",
    name: "Azithromycin 500mg",
    category: "Antibiotic",
    price: 35,
    quantity: 30,
    expiryDate: "2027-02-28",
    manufacturer: "Zithromax",
    lowStockThreshold: 10,
  },
  {
    id: "med-010",
    name: "Vitamin D3 1000IU",
    category: "Supplement",
    price: 20,
    quantity: 200,
    expiryDate: "2028-01-01",
    manufacturer: "Nature's Best",
    lowStockThreshold: 10,
  },
];

export const SEED_ACCOUNTS: Account[] = [
  {
    id: "acc-001",
    username: "admin",
    password: "admin123",
    fullName: "Administrator",
    role: "admin",
    enabled: true,
    createdAt: new Date("2026-01-01").toISOString(),
  },
  {
    id: "acc-002",
    username: "cashier1",
    password: "cash123",
    fullName: "Ahmed Ali",
    role: "client",
    enabled: true,
    createdAt: new Date("2026-01-15").toISOString(),
  },
];
