/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Account = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'enabled' : IDL.Bool,
  'pharmacyId' : IDL.Text,
});
export const InventoryAdjustmentRecord = IDL.Record({
  'inventoryDifferences' : IDL.Opt(IDL.Text),
  'adjustmentAmount' : IDL.Nat,
  'timestamp' : IDL.Text,
  'pharmacyId' : IDL.Text,
  'medicineId' : IDL.Text,
  'adjustedBy' : IDL.Text,
  'reason' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Text,
  'manufacturer' : IDL.Text,
  'retailPrice' : IDL.Float64,
  'purchasePrice' : IDL.Float64,
  'lowStockThreshold' : IDL.Nat,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'pharmacyId' : IDL.Text,
  'price' : IDL.Float64,
  'rackNumber' : IDL.Text,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Text,
  'purchasePrice' : IDL.Float64,
  'date' : IDL.Text,
  'discountAmount' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'discountPercent' : IDL.Float64,
  'addedByName' : IDL.Text,
  'addedBy' : IDL.Text,
  'quantity' : IDL.Nat,
  'pharmacyId' : IDL.Text,
  'medicineId' : IDL.Text,
  'netPurchasePrice' : IDL.Float64,
  'medicineName' : IDL.Text,
});
export const SaleItem = IDL.Record({
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'medicineId' : IDL.Text,
  'subtotal' : IDL.Float64,
  'medicineName' : IDL.Text,
});
export const Sale = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'soldBy' : IDL.Text,
  'date' : IDL.Text,
  'patientPhone' : IDL.Text,
  'soldByName' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'patientName' : IDL.Text,
  'discount' : IDL.Float64,
  'pharmacyId' : IDL.Text,
  'items' : IDL.Vec(SaleItem),
  'subtotal' : IDL.Float64,
});
export const TransactionRecord = IDL.Record({
  'transactionType' : IDL.Text,
  'source' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Text,
  'pharmacyId' : IDL.Text,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Text,
});
export const UnauthorizedAccessAttempt = IDL.Record({
  'userId' : IDL.Text,
  'timestamp' : IDL.Text,
  'details' : IDL.Text,
  'pharmacyId' : IDL.Text,
  'resourceAttempted' : IDL.Text,
});
export const Pharmacy = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'expiresAt' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const SuperAdmin = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAccount' : IDL.Func([Account], [], []),
  'addInventoryAdjustmentRecord' : IDL.Func(
      [InventoryAdjustmentRecord],
      [],
      [],
    ),
  'addMedicine' : IDL.Func([Medicine], [], []),
  'addPharmacy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPurchase' : IDL.Func([PurchaseRecord], [], []),
  'addSale' : IDL.Func([Sale], [], []),
  'addTransactionRecord' : IDL.Func([TransactionRecord], [], []),
  'addUnauthorizedAccessAttempt' : IDL.Func(
      [UnauthorizedAccessAttempt],
      [],
      [],
    ),
  'changeSuperAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMedicine' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePharmacy' : IDL.Func([IDL.Text], [], []),
  'deleteSale' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Sale)], []),
  'getAccounts' : IDL.Func([IDL.Text], [IDL.Vec(Account)], ['query']),
  'getInventoryAdjustmentRecords' : IDL.Func(
      [],
      [IDL.Vec(InventoryAdjustmentRecord)],
      ['query'],
    ),
  'getMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'getMedicinesByCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesByPriceRange' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesExpiringSoon' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesLowStock' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'getPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
  'getPurchases' : IDL.Func([IDL.Text], [IDL.Vec(PurchaseRecord)], ['query']),
  'getSales' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
  'getSuperAdmin' : IDL.Func([], [IDL.Opt(SuperAdmin)], ['query']),
  'getTransactionRecords' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getUnauthorizedAccessAttempts' : IDL.Func(
      [],
      [IDL.Vec(UnauthorizedAccessAttempt)],
      ['query'],
    ),
  'setupSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateMedicineQuantity' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updatePharmacyStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Account)],
      ['query'],
    ),
  'verifySuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Account = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'enabled' : IDL.Bool,
    'pharmacyId' : IDL.Text,
  });
  const InventoryAdjustmentRecord = IDL.Record({
    'inventoryDifferences' : IDL.Opt(IDL.Text),
    'adjustmentAmount' : IDL.Nat,
    'timestamp' : IDL.Text,
    'pharmacyId' : IDL.Text,
    'medicineId' : IDL.Text,
    'adjustedBy' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Text,
    'manufacturer' : IDL.Text,
    'retailPrice' : IDL.Float64,
    'purchasePrice' : IDL.Float64,
    'lowStockThreshold' : IDL.Nat,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'pharmacyId' : IDL.Text,
    'price' : IDL.Float64,
    'rackNumber' : IDL.Text,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Text,
    'purchasePrice' : IDL.Float64,
    'date' : IDL.Text,
    'discountAmount' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'discountPercent' : IDL.Float64,
    'addedByName' : IDL.Text,
    'addedBy' : IDL.Text,
    'quantity' : IDL.Nat,
    'pharmacyId' : IDL.Text,
    'medicineId' : IDL.Text,
    'netPurchasePrice' : IDL.Float64,
    'medicineName' : IDL.Text,
  });
  const SaleItem = IDL.Record({
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'medicineId' : IDL.Text,
    'subtotal' : IDL.Float64,
    'medicineName' : IDL.Text,
  });
  const Sale = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'soldBy' : IDL.Text,
    'date' : IDL.Text,
    'patientPhone' : IDL.Text,
    'soldByName' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'patientName' : IDL.Text,
    'discount' : IDL.Float64,
    'pharmacyId' : IDL.Text,
    'items' : IDL.Vec(SaleItem),
    'subtotal' : IDL.Float64,
  });
  const TransactionRecord = IDL.Record({
    'transactionType' : IDL.Text,
    'source' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Text,
    'pharmacyId' : IDL.Text,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Text,
  });
  const UnauthorizedAccessAttempt = IDL.Record({
    'userId' : IDL.Text,
    'timestamp' : IDL.Text,
    'details' : IDL.Text,
    'pharmacyId' : IDL.Text,
    'resourceAttempted' : IDL.Text,
  });
  const Pharmacy = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'expiresAt' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SuperAdmin = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
  });
  
  return IDL.Service({
    'addAccount' : IDL.Func([Account], [], []),
    'addInventoryAdjustmentRecord' : IDL.Func(
        [InventoryAdjustmentRecord],
        [],
        [],
      ),
    'addMedicine' : IDL.Func([Medicine], [], []),
    'addPharmacy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPurchase' : IDL.Func([PurchaseRecord], [], []),
    'addSale' : IDL.Func([Sale], [], []),
    'addTransactionRecord' : IDL.Func([TransactionRecord], [], []),
    'addUnauthorizedAccessAttempt' : IDL.Func(
        [UnauthorizedAccessAttempt],
        [],
        [],
      ),
    'changeSuperAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMedicine' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePharmacy' : IDL.Func([IDL.Text], [], []),
    'deleteSale' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Sale)], []),
    'getAccounts' : IDL.Func([IDL.Text], [IDL.Vec(Account)], ['query']),
    'getInventoryAdjustmentRecords' : IDL.Func(
        [],
        [IDL.Vec(InventoryAdjustmentRecord)],
        ['query'],
      ),
    'getMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'getMedicinesByCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesByPriceRange' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesExpiringSoon' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesLowStock' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
    'getPurchases' : IDL.Func([IDL.Text], [IDL.Vec(PurchaseRecord)], ['query']),
    'getSales' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
    'getSuperAdmin' : IDL.Func([], [IDL.Opt(SuperAdmin)], ['query']),
    'getTransactionRecords' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getUnauthorizedAccessAttempts' : IDL.Func(
        [],
        [IDL.Vec(UnauthorizedAccessAttempt)],
        ['query'],
      ),
    'setupSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateMedicineQuantity' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updatePharmacyStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Account)],
        ['query'],
      ),
    'verifySuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };