/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Account {
    id: string;
    username: string;
    password: string;
    createdAt: string;
    role: string;
    fullName: string;
    enabled: boolean;
    pharmacyId: string;
}
export interface Pharmacy {
    id: string;
    status: string;
    expiresAt: string;
    name: string;
    createdAt: string;
    address: string;
    phone: string;
}
export interface SuperAdmin {
    username: string;
    password: string;
}
export interface PurchaseRecord {
    id: string;
    purchasePrice: number;
    date: string;
    discountAmount: number;
    totalCost: number;
    discountPercent: number;
    addedByName: string;
    addedBy: string;
    quantity: bigint;
    pharmacyId: string;
    medicineId: string;
    netPurchasePrice: number;
    medicineName: string;
}
export interface InventoryAdjustmentRecord {
    inventoryDifferences?: string;
    adjustmentAmount: bigint;
    timestamp: string;
    pharmacyId: string;
    medicineId: string;
    adjustedBy: string;
    reason: string;
}
export interface Medicine {
    id: string;
    manufacturer: string;
    retailPrice: number;
    purchasePrice: number;
    lowStockThreshold: bigint;
    expiryDate: string;
    name: string;
    quantity: bigint;
    category: string;
    pharmacyId: string;
    price: number;
    rackNumber: string;
}
export interface Sale {
    id: string;
    total: number;
    soldBy: string;
    date: string;
    patientPhone: string;
    soldByName: string;
    invoiceNumber: string;
    patientName: string;
    discount: number;
    pharmacyId: string;
    items: Array<SaleItem>;
    subtotal: number;
}
export interface UnauthorizedAccessAttempt {
    userId: string;
    timestamp: string;
    details: string;
    pharmacyId: string;
    resourceAttempted: string;
}
export interface SaleItem {
    quantity: bigint;
    unitPrice: number;
    medicineId: string;
    subtotal: number;
    medicineName: string;
}
export interface TransactionRecord {
    transactionType: string;
    source: string;
    performedBy: string;
    timestamp: string;
    pharmacyId: string;
    amount: number;
    transactionId: string;
}
export interface backendInterface {
    addAccount(account: Account): Promise<void>;
    addInventoryAdjustmentRecord(record: InventoryAdjustmentRecord): Promise<void>;
    addMedicine(medicine: Medicine): Promise<void>;
    addPharmacy(id: string, name: string, address: string, phone: string, createdAt: string): Promise<void>;
    addPurchase(record: PurchaseRecord): Promise<void>;
    addSale(sale: Sale): Promise<void>;
    addTransactionRecord(record: TransactionRecord): Promise<void>;
    addUnauthorizedAccessAttempt(attempt: UnauthorizedAccessAttempt): Promise<void>;
    changeSuperAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    deleteAccount(id: string, pharmacyId: string): Promise<void>;
    deleteMedicine(id: string, pharmacyId: string): Promise<void>;
    deletePharmacy(id: string): Promise<void>;
    deleteSale(id: string, pharmacyId: string): Promise<Sale | null>;
    getAccounts(pharmacyId: string): Promise<Array<Account>>;
    getInventoryAdjustmentRecords(): Promise<Array<InventoryAdjustmentRecord>>;
    getMedicines(pharmacyId: string): Promise<Array<Medicine>>;
    getMedicinesByCategory(pharmacyId: string, category: string): Promise<Array<Medicine>>;
    getMedicinesByPriceRange(pharmacyId: string, minPrice: number, maxPrice: number): Promise<Array<Medicine>>;
    getMedicinesExpiringSoon(pharmacyId: string): Promise<Array<Medicine>>;
    getMedicinesLowStock(pharmacyId: string): Promise<Array<Medicine>>;
    getPharmacies(): Promise<Array<Pharmacy>>;
    getPurchases(pharmacyId: string): Promise<Array<PurchaseRecord>>;
    getSales(pharmacyId: string): Promise<Array<Sale>>;
    getSuperAdmin(): Promise<SuperAdmin | null>;
    getTransactionRecords(): Promise<Array<TransactionRecord>>;
    getUnauthorizedAccessAttempts(): Promise<Array<UnauthorizedAccessAttempt>>;
    setupSuperAdmin(username: string, password: string): Promise<boolean>;
    updateAccount(id: string, pharmacyId: string, username: string, password: string, fullName: string, role: string, enabled: boolean): Promise<void>;
    updateMedicine(id: string, pharmacyId: string, name: string, category: string, price: number, purchasePrice: number, retailPrice: number, quantity: bigint, expiryDate: string, manufacturer: string, lowStockThreshold: bigint, rackNumber: string): Promise<void>;
    updateMedicineQuantity(id: string, pharmacyId: string, newQuantity: bigint): Promise<void>;
    updatePharmacyStatus(id: string, status: string, expiresAt: string): Promise<void>;
    verifyAccount(pharmacyId: string, username: string, password: string): Promise<Account | null>;
    verifySuperAdmin(username: string, password: string): Promise<boolean>;
}
import type { Account as _Account, InventoryAdjustmentRecord as _InventoryAdjustmentRecord, Sale as _Sale, SuperAdmin as _SuperAdmin } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAccount(arg0: Account): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0);
            return result;
        }
    }
    async addInventoryAdjustmentRecord(arg0: InventoryAdjustmentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryAdjustmentRecord(to_candid_InventoryAdjustmentRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryAdjustmentRecord(to_candid_InventoryAdjustmentRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMedicine(arg0: Medicine): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0);
            return result;
        }
    }
    async addPharmacy(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPharmacy(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPharmacy(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPurchase(arg0: PurchaseRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchase(arg0);
            return result;
        }
    }
    async addSale(arg0: Sale): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addTransactionRecord(arg0: TransactionRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransactionRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransactionRecord(arg0);
            return result;
        }
    }
    async addUnauthorizedAccessAttempt(arg0: UnauthorizedAccessAttempt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUnauthorizedAccessAttempt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUnauthorizedAccessAttempt(arg0);
            return result;
        }
    }
    async changeSuperAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeSuperAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeSuperAdminPassword(arg0, arg1);
            return result;
        }
    }
    async deleteAccount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0, arg1);
            return result;
        }
    }
    async deleteMedicine(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0, arg1);
            return result;
        }
    }
    async deletePharmacy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePharmacy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePharmacy(arg0);
            return result;
        }
    }
    async deleteSale(arg0: string, arg1: string): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSale(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSale(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccounts(arg0: string): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccounts(arg0);
            return result;
        }
    }
    async getInventoryAdjustmentRecords(): Promise<Array<InventoryAdjustmentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryAdjustmentRecords();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryAdjustmentRecords();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicines(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicines(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicines(arg0);
            return result;
        }
    }
    async getMedicinesByCategory(arg0: string, arg1: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByCategory(arg0, arg1);
            return result;
        }
    }
    async getMedicinesByPriceRange(arg0: string, arg1: number, arg2: number): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByPriceRange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByPriceRange(arg0, arg1, arg2);
            return result;
        }
    }
    async getMedicinesExpiringSoon(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesExpiringSoon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesExpiringSoon(arg0);
            return result;
        }
    }
    async getMedicinesLowStock(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesLowStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesLowStock(arg0);
            return result;
        }
    }
    async getPharmacies(): Promise<Array<Pharmacy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacies();
            return result;
        }
    }
    async getPurchases(arg0: string): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchases(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchases(arg0);
            return result;
        }
    }
    async getSales(arg0: string): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales(arg0);
            return result;
        }
    }
    async getSuperAdmin(): Promise<SuperAdmin | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuperAdmin();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuperAdmin();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionRecords(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionRecords();
            return result;
        }
    }
    async getUnauthorizedAccessAttempts(): Promise<Array<UnauthorizedAccessAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnauthorizedAccessAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnauthorizedAccessAttempts();
            return result;
        }
    }
    async setupSuperAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setupSuperAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupSuperAdmin(arg0, arg1);
            return result;
        }
    }
    async updateAccount(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateMedicine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: bigint, arg8: string, arg9: string, arg10: bigint, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async updateMedicineQuantity(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicineQuantity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicineQuantity(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePharmacyStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePharmacyStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePharmacyStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyAccount(arg0: string, arg1: string, arg2: string): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAccount(arg0, arg1, arg2);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAccount(arg0, arg1, arg2);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifySuperAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySuperAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySuperAdmin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_InventoryAdjustmentRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryAdjustmentRecord): InventoryAdjustmentRecord {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SuperAdmin]): SuperAdmin | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inventoryDifferences: [] | [string];
    adjustmentAmount: bigint;
    timestamp: string;
    pharmacyId: string;
    medicineId: string;
    adjustedBy: string;
    reason: string;
}): {
    inventoryDifferences?: string;
    adjustmentAmount: bigint;
    timestamp: string;
    pharmacyId: string;
    medicineId: string;
    adjustedBy: string;
    reason: string;
} {
    return {
        inventoryDifferences: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.inventoryDifferences)),
        adjustmentAmount: value.adjustmentAmount,
        timestamp: value.timestamp,
        pharmacyId: value.pharmacyId,
        medicineId: value.medicineId,
        adjustedBy: value.adjustedBy,
        reason: value.reason
    };
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryAdjustmentRecord>): Array<InventoryAdjustmentRecord> {
    return value.map((x)=>from_candid_InventoryAdjustmentRecord_n5(_uploadFile, _downloadFile, x));
}
function to_candid_InventoryAdjustmentRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryAdjustmentRecord): _InventoryAdjustmentRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inventoryDifferences?: string;
    adjustmentAmount: bigint;
    timestamp: string;
    pharmacyId: string;
    medicineId: string;
    adjustedBy: string;
    reason: string;
}): {
    inventoryDifferences: [] | [string];
    adjustmentAmount: bigint;
    timestamp: string;
    pharmacyId: string;
    medicineId: string;
    adjustedBy: string;
    reason: string;
} {
    return {
        inventoryDifferences: value.inventoryDifferences ? candid_some(value.inventoryDifferences) : candid_none(),
        adjustmentAmount: value.adjustmentAmount,
        timestamp: value.timestamp,
        pharmacyId: value.pharmacyId,
        medicineId: value.medicineId,
        adjustedBy: value.adjustedBy,
        reason: value.reason
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
